### ISSUE TITLE
can't plot Riyadh with coordinates

### ISSUE THREAD

**Issue by jic007** [benyamindsmith/starBliss#9]
library(starBliss)
plot_starmap( "Riyadh, Saudi Arabia", line1_text = "first line",
              line2_text =" second")

doesn't display cooridnates and doubt the chart is for the location 

could you please help

**Comment by benyamindsmith** [comment]
@jic007 thank you for using the package and finding this issue

This is what I got from running your code.

![image](https://user-images.githubusercontent.com/46410142/218780525-e9900ff2-cd72-44c6-9c99-173a9f01bee3.png)

From MapsForMoments, the map generated is: 

![image](https://user-images.githubusercontent.com/46410142/218780436-91e90a4b-c0a4-453f-b0a7-b5093a943920.png)

I believe the issue is with the rotation by the longitude parameter in the CRS. 

I'll look into the problem. Let me know if you find anything as well!

**Comment by jic007** [comment]
> @jic007 thank you for using the package and finding this issue
> 
> This is what I got from running your code.
> 
> ![image](https://user-images.githubusercontent.com/46410142/218780525-e9900ff2-cd72-44c6-9c99-173a9f01bee3.png)
> 
> From MapsForMoments, the map generated is:
> 
> ![image](https://user-images.githubusercontent.com/46410142/218780436-91e90a4b-c0a4-453f-b0a7-b5093a943920.png)
> 
> I believe the issue is with the rotation by the longitude parameter in the CRS.
> 
> I'll look into the problem. Let me know if you find anything as well!

Hey Benyamin,
thank you for the feedback. got a solution? could you please share the code u used for MapsForMoments?

**Comment by benyamindsmith** [comment]
@jic007 I just looked at the MapsForMoments site (which `starBliss` is based on) here: https://mapsformoments.co.uk/9-star-map?step=design and saw that the the starmap is different

**Comment by benyamindsmith** [comment]
Just asked the question here: https://gis.stackexchange.com/questions/452565/how-to-calculate-the-crs-for-the-celestial-sphere Hopefully it will be clarified so that I can sort out the issue.
